### ISSUE TITLE
Reports failing or reporting ReportingPeriodUnmetDependencies

### ISSUE THREAD

**Issue by salanisor** [kube-reporting/metering-operator#1408]
This is a new deployment with ISCSI storage backing via a Linux VM on vmware. The metering operator deploys fine however sample reports finish with no report available [Ref-1] or reports show ReportingPeriodUnmetDependencies.

When following the [troubleshooting-guide](https://docs.openshift.com/container-platform/4.5/metering/metering-troubleshooting-debugging.html) I see many errors from the metering operator and Presto pods but unsure where to go from here.

In the reporting operator logs I see many errors pointing to the Persistent Volume path [Ref-2], however I've verified my storage backing to be wiped clean prior to mounting and even opened up permissions. And Presto is throwing runtime exceptions [Ref-3]. Any leads are greatly appreciated.

**Reference**

[1]
```
Error: failed to perform presto query (see operator logs for more details): presto: query failed (200 OK): "io.prestosql.spi.PrestoException: Partition location does not exist: file:/user/hive/warehouse/metering.db/report_openshift_metering_namespace_cpu_request"
```

[2]
```
 Failed to create directory: file:/user/hive/warehouse/metering.db/datasource_openshift_metering_pod_request_memory_bytes
```

[3]
```
2020-10-06T20:03:35.340Z	INFO	dispatcher-query-1665	io.prestosql.event.QueryMonitor	TIMELINE: Query 20201006_200334_04873_f66pt :: Transaction:[c9295039-f48f-4aec-b5b9-d411f94d2911] :: elapsed 390ms :: planning 272ms :: waiting 39ms :: scheduling 77ms :: running 5ms :: finishing 36ms :: begin 2020-10-06T20:03:34.941Z :: end 2020-10-06T20:03:35.331Z
2020-10-06T20:03:43.254Z	INFO	dispatcher-query-1661	io.prestosql.event.QueryMonitor	TIMELINE: Query 20201006_200343_04874_f66pt :: Transaction:[7b64266d-7953-43e3-8d2c-f3563d4a0624] :: elapsed 11ms :: planning 2ms :: waiting 0ms :: scheduling 3ms :: running 3ms :: finishing 3ms :: begin 2020-10-06T20:03:43.241Z :: end 2020-10-06T20:03:43.252Z
2020-10-06T20:04:01.455Z	INFO	dispatcher-query-1670	io.prestosql.event.QueryMonitor	TIMELINE: Query 20201006_200401_04875_f66pt :: Transaction:[0af0a7e6-c75e-4bdb-92a3-af0f047bbcd4] :: elapsed 51ms :: planning 24ms :: waiting 23ms :: scheduling 25ms :: running 2ms :: finishing 0ms :: begin 2020-10-06T20:04:01.402Z :: end 2020-10-06T20:04:01.453Z
2020-10-06T20:04:01.540Z	ERROR	transaction-finishing-27	com.google.common.util.concurrent.AbstractFuture	RuntimeException while executing runnable CallbackListener{io.prestosql.execution.QueryStateMachine$1@36d88eeb} with executor MoreExecutors.directExecutor()
io.prestosql.NotInTransactionException: Unknown transaction ID: 23405846-d29b-4d90-8ebe-426600c53cd7. Possibly expired? Commands ignored until end of transaction block
	at io.prestosql.transaction.InMemoryTransactionManager.getTransactionMetadata(InMemoryTransactionManager.java:258)
	at io.prestosql.transaction.InMemoryTransactionManager.getTransactionInfo(InMemoryTransactionManager.java:156)
	at io.prestosql.transaction.TransactionManager.isAutoCommit(TransactionManager.java:37)
	at io.prestosql.execution.QueryStateMachine.lambda$transitionToFailed$12(QueryStateMachine.java:812)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.prestosql.execution.QueryStateMachine.transitionToFailed(QueryStateMachine.java:811)
	at io.prestosql.execution.QueryStateMachine$1.onFailure(QueryStateMachine.java:779)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1029)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:757)
	at com.google.common.util.concurrent.Futures$NonCancellationPropagatingFuture.run(Futures.java:777)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1029)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:757)
	at com.google.common.util.concurrent.Futures$NonCancellationPropagatingFuture.run(Futures.java:777)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1029)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:92)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1029)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.afterRanInterruptibly(TrustedListenableFutureTask.java:133)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:80)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Operator version**
```
   API Version:       operators.coreos.com/v1alpha1
    Kind:              InstallPlan
    Name:              install-4qk7d
    Namespace:         openshift-metering
    Resource Version:  271873
  Installed CSV:       metering-operator.4.5.0-202009190219.p0
```
**log files**
[metering-pvc.txt](https://github.com/kube-reporting/metering-operator/files/5336988/metering-pvc.txt)
[presto.log](https://github.com/kube-reporting/metering-operator/files/5336989/presto.log)
[reporting-operator.log](https://github.com/kube-reporting/metering-operator/files/5336991/reporting-operator.log)
[MeteringConfig.txt](https://github.com/kube-reporting/metering-operator/files/5336998/MeteringConfig.txt)
[storagecontents.txt](https://github.com/kube-reporting/metering-operator/files/5340860/storagecontents.txt)

**Comment by salanisor** [comment]
changing the owner to nobody:nobody resolved my disk permission errors.
